# Generated by Django 4.1.13 on 2024-03-05 20:37

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('idioma', models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('it', 'Italiano'), ('de', 'Alemán'), ('pt', 'Portugués'), ('ko', 'Koreano')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Novela',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('sinopsis', models.TextField(blank=True)),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('genero', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('emision', 'Emision'), ('completo', 'Completo'), ('pausa', 'Pausado'), ('abandonado', 'Abandonado')], max_length=100)),
                ('url', models.CharField(max_length=1000)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='EstructuraSitio',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('orden_selector', models.PositiveIntegerField(default=0)),
                ('selector', models.CharField(blank=True, max_length=100)),
                ('marcador', models.CharField(blank=True, max_length=100)),
                ('tipo_selector', models.CharField(blank=True, max_length=100)),
                ('nombre_selector', models.CharField(blank=True, max_length=100)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoCapitulo',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('texto', models.TextField(blank=True)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.capitulo')),
            ],
        ),
        migrations.AddField(
            model_name='capitulo',
            name='novela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.novela'),
        ),
    ]
