# Generated by Django 4.1.13 on 2024-04-03 01:55

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('novela_id', models.CharField(blank=True, max_length=100)),
                ('nombre', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoCapitulo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('novela_id', models.CharField(blank=True, max_length=100)),
                ('capitulo_id', models.CharField(blank=True, max_length=100)),
                ('texto', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstructuraSitio',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('sitio_id', models.CharField(blank=True, max_length=100)),
                ('orden_selector', models.PositiveIntegerField(default=0)),
                ('selector', models.CharField(blank=True, max_length=100)),
                ('marcador', models.CharField(blank=True, max_length=100)),
                ('tipo_selector', models.CharField(blank=True, max_length=100)),
                ('nombre_selector', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Novela',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('sitio_id', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('sinopsis', models.TextField(blank=True)),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('genero', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('emision', 'Emision'), ('completo', 'Completo'), ('pausa', 'Pausado'), ('abandonado', 'Abandonado')], max_length=100)),
                ('url', models.CharField(max_length=1000)),
                ('imagen_url', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('idioma', models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('it', 'Italiano'), ('de', 'Alemán'), ('pt', 'Portugués'), ('ko', 'Koreano')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
