# Generated by Django 4.1.13 on 2024-06-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='novela',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='novela',
            name='status',
            field=models.CharField(blank=True, choices=[('emision', 'Emisión'), ('completo', 'Completo'), ('pausa', 'Pausado'), ('abandonado', 'Abandonado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='novela',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='idioma',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('it', 'Italiano'), ('de', 'Alemán'), ('pt', 'Portugués'), ('ko', 'Koreano')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
