# Generated by Django 4.1.13 on 2024-03-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulo',
            name='novelas',
        ),
        migrations.RemoveField(
            model_name='contenidocapitulo',
            name='capitulo',
        ),
        migrations.RemoveField(
            model_name='estructurasitio',
            name='sitio',
        ),
        migrations.RemoveField(
            model_name='novela',
            name='sitio',
        ),
        migrations.AddField(
            model_name='capitulo',
            name='novela_id',
            field=models.CharField(blank=True, choices=[('65e7ed3d9297a4c7c5aaaeef', "MARTIAL KING'S RETIRED LIFE"), ('65e874957a145405d0b24bf5', 'CULTIVATION CHAT GROUP')], max_length=100),
        ),
        migrations.AddField(
            model_name='contenidocapitulo',
            name='capitulo_id',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
        migrations.AddField(
            model_name='contenidocapitulo',
            name='novela_id',
            field=models.CharField(blank=True, choices=[('65e7ed3d9297a4c7c5aaaeef', "MARTIAL KING'S RETIRED LIFE"), ('65e874957a145405d0b24bf5', 'CULTIVATION CHAT GROUP')], max_length=100),
        ),
        migrations.AddField(
            model_name='estructurasitio',
            name='sitio_id',
            field=models.CharField(blank=True, choices=[('65e7e1707963e189aa4c1256', 'Novel Bin'), ('65e7e19f7963e189aa4c1258', 'Fortune Eternal')], max_length=100),
        ),
        migrations.AddField(
            model_name='novela',
            name='sitio_id',
            field=models.CharField(blank=True, choices=[('65e7e1707963e189aa4c1256', 'Novel Bin'), ('65e7e19f7963e189aa4c1258', 'Fortune Eternal')], max_length=100),
        ),
    ]
