# Generated by Django 4.1.13 on 2024-02-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estructurasitio',
            name='marcador',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
