# Generated by Django 4.1.13 on 2024-02-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_estructurasitio_marcador'),
    ]

    operations = [
        migrations.AddField(
            model_name='estructurasitio',
            name='orden_selector',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
