# Generated by Django 4.1.13 on 2024-03-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_capitulo_created_at_capitulo_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='novela_id',
            field=models.CharField(blank=True, choices=[('65e7ed3d9297a4c7c5aaaeef', "MARTIAL KING'S RETIRED LIFE"), ('65e874957a145405d0b24bf5', 'CULTIVATION CHAT GROUP'), ('65efbb2ceb6e829adc4a104a', "EMPEROR'S DOMINATION"), ('65efbb58eb6e829adc4a104c', 'BECOMING IMMORTAL THROUGH GETTING MARRIED'), ('65f1af5d4285ef9618f6b28f', 'AS AN IMMORTAL, I ONLY LEARN FORBIDDEN SKILLS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contenidocapitulo',
            name='novela_id',
            field=models.CharField(blank=True, choices=[('65e7ed3d9297a4c7c5aaaeef', "MARTIAL KING'S RETIRED LIFE"), ('65e874957a145405d0b24bf5', 'CULTIVATION CHAT GROUP'), ('65efbb2ceb6e829adc4a104a', "EMPEROR'S DOMINATION"), ('65efbb58eb6e829adc4a104c', 'BECOMING IMMORTAL THROUGH GETTING MARRIED'), ('65f1af5d4285ef9618f6b28f', 'AS AN IMMORTAL, I ONLY LEARN FORBIDDEN SKILLS')], max_length=100),
        ),
    ]
