# Generated by Django 4.1.13 on 2024-02-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_estructurasitio_orden_selector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='nombre',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
