# Generated by Django 4.1.13 on 2024-03-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_capitulo_novela_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='novela_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contenidocapitulo',
            name='capitulo_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contenidocapitulo',
            name='novela_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='estructurasitio',
            name='sitio_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='novela',
            name='sitio_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
